import type { DeviceProfile } from './types';

export const deviceProfiles: Record<string, DeviceProfile> = {
  iphone_15_pro: {
    width: 393,
    height: 852,
    pixel_ratio: 3,
    safe_area_top: 59,
    safe_area_bottom: 34,
    corner_radius: 55,
    notch_type: 'dynamic_island',
  },
  iphone_15_pro_max: {
    width: 430,
    height: 932,
    pixel_ratio: 3,
    safe_area_top: 59,
    safe_area_bottom: 34,
    corner_radius: 55,
    notch_type: 'dynamic_island',
  },
  iphone_15: {
    width: 390,
    height: 844,
    pixel_ratio: 3,
    safe_area_top: 59,
    safe_area_bottom: 34,
    corner_radius: 55,
    notch_type: 'dynamic_island',
  },
  iphone_14: {
    width: 390,
    height: 844,
    pixel_ratio: 3,
    safe_area_top: 59,
    safe_area_bottom: 34,
    corner_radius: 47,
    notch_type: 'dynamic_island',
  },
  iphone_se: {
    width: 375,
    height: 667,
    pixel_ratio: 2,
    safe_area_top: 20,
    safe_area_bottom: 0,
    corner_radius: 0,
    notch_type: 'none',
  },
  pixel_8: {
    width: 412,
    height: 915,
    pixel_ratio: 2.625,
    safe_area_top: 36,
    safe_area_bottom: 24,
    corner_radius: 28,
    notch_type: 'punch_hole',
  },
  pixel_9_pro: {
    width: 412,
    height: 922,
    pixel_ratio: 2.75,
    safe_area_top: 36,
    safe_area_bottom: 24,
    corner_radius: 30,
    notch_type: 'punch_hole',
  },
  samsung_s24: {
    width: 360,
    height: 780,
    pixel_ratio: 3,
    safe_area_top: 36,
    safe_area_bottom: 24,
    corner_radius: 26,
    notch_type: 'punch_hole',
  },
  samsung_s24_ultra: {
    width: 412,
    height: 915,
    pixel_ratio: 3.12,
    safe_area_top: 36,
    safe_area_bottom: 24,
    corner_radius: 30,
    notch_type: 'punch_hole',
  },
  generic: {
    width: 390,
    height: 844,
    pixel_ratio: 2,
    safe_area_top: 44,
    safe_area_bottom: 34,
    corner_radius: 40,
    notch_type: 'none',
  },
};
